# ClusterSecretStore for Infisical
# Requires manual secret created first:
#   kubectl create namespace external-secrets
#   kubectl create secret generic universal-auth-credentials \
#     --from-literal=clientId=<INFISICAL_CLIENT_ID> \
#     --from-literal=clientSecret=<INFISICAL_CLIENT_SECRET> \
#     -n external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: universal-auth-credentials
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: universal-auth-credentials
            namespace: external-secrets
            key: clientSecret
      secretsScope:
        projectSlug: mothership-s0-ew
        environmentSlug: prod
