# ExternalSecret for Netdata claiming credentials
# Pulls from Infisical: /netdata/CLAIM_TOKEN, CLAIM_ROOMS
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netdata-claiming
  namespace: netdata
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-netdata
  target:
    name: netdata-claiming
    creationPolicy: Owner
  data:
    - secretKey: NETDATA_CLAIM_TOKEN
      remoteRef:
        key: CLAIMING_TOKEN
    - secretKey: NETDATA_CLAIM_ROOMS
      remoteRef:
        key: CLAIMING_ROOM
