# ExternalSecret for Tailscale OAuth credentials
# Pulls from Infisical: /tailscale-operator/CLIENT_ID, CLIENT_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: CLIENT_ID
        property: value
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        key: CLIENT_SECRET
        property: value
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
